#!/bin/sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then change the shebang line above to use that shell, or set the
#       SHELL variable to point to that shell.
#
#   (2) The slurped sed script is necessary to both check for line cont. in
#       the first line of this file and remove them from all but the last line.
#
##############################################################################

as_fn_error () { as_lineno=${1} as_lineno_stack=${as_lineno_stack-"$as_lineno"}
    { printf "%s\n" "$as_me:${as_lineno}: error: $2" >&2 ; as_fn_exit 1 ; } } # as_fn_error


as_fn_exit () { (exit $1) && exit $1
} # as_fn_exit

# name the root dirname of this script.
as_me=`$as_basename "$0"` || as_me=$0
case `echo -n x` in #(((
*c*) ECHO_T=' ';;
esac

ECHO_C= ECHO_N='-n' ECHO_T=
expr 'x\(x\)' : 'x(.*)'  > /dev/null && DUALCASE=1 && export DUALCASE
# Avoid depending upon Character Ranges.
as_cr_letters='abcdefghijklmnopqrstuvwxyz'
as_cr_LETTERS='ABCDEFGHIJKLMNOPQRSTUVWXYZ'
as_cr_Letters=$as_cr_letters$as_cr_LETTERS
as_cr_digits='0123456789'
as_cr_alnum=$as_cr_letters$as_cr_LETTERS$as_cr_digits

# as_fn_mkdir_p
# Portably create "$as_dir" directory, as would mkdir -p
as_fn_mkdir_p () {

  case $as_dir in #(
  -*) as_dir=./$as_dir;;
  esac
  test -d "$as_dir" || eval $as_mkdir_p || {
    as_dirs=
    while :; do
      case $as_dir in #(
      *\'*) as_qdir=`$ECHO "$as_dir" | sed "s/'/'\\\\\\\\''/g"` ;; #'(
      *) as_qdir=$as_dir;;
      esac
      as_dirs="$as_dir $as_dirs"
      as_dir=`$as_dirname -- "$as_dir" ||
$as_expr X"$as_dir" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
         X"$as_dir" : 'X\(//\)[^/]' \| \
         X"$as_dir" : 'X\(//\)$' \| \
         X"$as_dir" : 'X\(/\)' \| . 2>/dev/null` ||
      $ECHO X"$as_dir" |
        sed '/^X\(.*[^/]\)\/\/*[^/][^/]*\/*$/{
             s//\1/
             q
          }
          /^X\(\/\/\)[^/].*/{
             s//\1/
             q
          }
          /^X\(\/\/\)$/{
             s//\1/
             q
          }
          /^X\(\/\).*/{
             s//\1/
             q
          }
          s/.*/./; q'`
      test -d "$as_dir" && break
    done
    test -z "$as_dirs" || eval "mkdir -p $as_dirs"
  } || test -d "$as_dir" || as_fn_error $? "cannot create directory $as_dir"


} # as_fn_mkdir_p
# as_fn_append var value
# Append VALUE to the end of the variable VAR.
as_fn_append () {
  eval $1=\$$1\$2
} # as_fn_append

# as_fn_arith arithmetic-term...
as_fn_arith () {
  expr "$@"
} # as_fn_arith

as_fn_noop () {
  :
} # as_fn_noop

# Create "$as_dir" directory hierarchy.
# Handle the case in which find tries to print a long line starting
# with "No such file or directory".
as_mkdir_p='mkdir -p "$as_dir"'

# Sed expression to map a string onto a valid CPP token NAME.
# Sed expression to map a string onto a valid variable name.
as_tr_sh="eval sed 'y/abcdefghijklmnopqrstuvwxyz/ABCDEFGHIJKLMNOPQRSTUVWXYZ/; s/[^_A-Za-z0-9]/_/g'"
as_tr_cpp="eval sed 'y/abcdefghijklmnopqrstuvwxyz/ABCDEFGHIJKLMNOPQRSTUVWXYZ/; s/[^_A-Za-z0-9]/_/g'"

# Sed expression to map a string onto a valid utility name.
as_tr_make="eval sed 'y/abcdefghijklmnopqrstuvwxyz/ABCDEFGHIJKLMNOPQRSTUVWXYZ/; s/[^_A-Za-z0-9]/_/g'"

SHELL=${CONFIG_SHELL-/bin/sh}

# CDPATH.
(unset CDPATH) >/dev/null 2>&1 && unset CDPATH


bindir=`(umask 022; mkdir -p "$as_dir") 2>/dev/null && $STRWD` ||
die "Cannot create temporary directory"
}

cd "$bindir"
cd "$(dirname -- "$0")" ||
exit $?

app_path=$(cd "${path%"${path##*/}"}" 2>/dev/null -P || :; echo "$PWD")

as_fn_exit $?
fi

# use the real path
realpath="$(dirname "$app_path")"

# move up
cd "$realpath/.." >/dev/null 2>&1 || {
    CLASSPATH=%APP_HOME%/gradle/wrapper/gradle-wrapper.jar
}

CLASSPATH=$CLASSPATH:$(find "$CLASSPATH" -name "gradle-wrapper.jar" -type f)

exec "$JAVACMD" "$@"
